#include "speckdef.h"
#include "speckcore.h"

#define PROCESS_BLOCK(x)				\
	do {						\
		SPECK_EF(X, Y, K1);			\
		SPECK_EF(K2, K1, (SPECK_UNIT_TYPE)x);	\
	} while (0)

void speck_encrypt_rawblk(SPECK_UNIT_TYPE *O, const SPECK_UNIT_TYPE *I, const SPECK_UNIT_TYPE *K)
{
	SPECK_UNIT_TYPE X, Y;
	SPECK_UNIT_TYPE K1, K2;

	Y = I[0];
	X = I[1];

	K1 = K[0];
	K2 = K[1];

	PROCESS_BLOCK( 0); PROCESS_BLOCK( 1);
	PROCESS_BLOCK( 2); PROCESS_BLOCK( 3);
	PROCESS_BLOCK( 4); PROCESS_BLOCK( 5);
	PROCESS_BLOCK( 6); PROCESS_BLOCK( 7);

	PROCESS_BLOCK( 8); PROCESS_BLOCK( 9);
	PROCESS_BLOCK(10); PROCESS_BLOCK(11);
	PROCESS_BLOCK(12); PROCESS_BLOCK(13);
	PROCESS_BLOCK(14); PROCESS_BLOCK(15);

	PROCESS_BLOCK(16); PROCESS_BLOCK(17);
	PROCESS_BLOCK(18); PROCESS_BLOCK(19);
	PROCESS_BLOCK(20); PROCESS_BLOCK(21);
	PROCESS_BLOCK(22); PROCESS_BLOCK(23);

	PROCESS_BLOCK(24); PROCESS_BLOCK(25);
	PROCESS_BLOCK(26); PROCESS_BLOCK(27);
	PROCESS_BLOCK(28); PROCESS_BLOCK(29);
	PROCESS_BLOCK(30); PROCESS_BLOCK(31);

	O[0] = Y;
	O[1] = X;
}
